name: Build Fresh AAB

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.22.0

      - name: Create Fresh Project
        run: flutter create tempapp

      - name: Replace Main Dart
        run: cp lib/main.dart tempapp/lib/main.dart

      - name: Build AAB
        run: |
          cd tempapp
          flutter pub get
          flutter build appbundle

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: tempapp/build/app/outputs/bundle/release/app-release.aab
